name: Auto Deploy to Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

   - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@master
      with:
        # Perhatikan: Di sini kita panggil NAMA KUNCI-nya, bukan isinya
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }} # Ganti 'key' jadi 'password'
        port: 22 # 22 untuk SSH
        script: |
          cd /var/www/html
          git pull origin main
